### ISSUE TITLE
Pipeline mnist gives an error during pipeline run

### ISSUE THREAD

**Issue by dalbhanj** [aws-samples/eks-kubeflow-workshop#44]
Notebook affected: https://github.com/aws-samples/eks-kubeflow-workshop/blob/master/notebooks/05_Kubeflow_Pipeline/05_03_Pipeline_mnist.ipynb

After you submit pipeline, step 3 kubeflow-launch-tfjob fails with this error
Traceback (most recent call last):
  File "/ml/launch_tfjob.py", line 22, in <module>
    import launch_crd
ImportError: No module named launch_crd

**Comment by PatrickXYS** [comment]
@dalbhanj thank you for proposing the issue, I'll take it over and fix it up.

**Comment by Jeffwan** [comment]
@PatrickXYS I don't see this issue,  module `launch_crd ` should come from container image, What's the image we are using now? Is it a regression issue after your refactor?

**Comment by PatrickXYS** [comment]
Yes, it should come from container image, which should be the [image hosted by me](chuckshow/kubeflow-tfjob-launcher:latest). There's no `launch_crd` now. It should be a regression issue after my factor, I'm working on it.

**Comment by Jeffwan** [comment]
@PatrickXYS As we don't have CI now, try to make sure things work before check in.

**Comment by PatrickXYS** [comment]
It should be fixed by the merged PR, @dalbhanj  let us know if it's good to go.

**Comment by dalbhanj** [comment]
This isn't resolved yet bcoz it only works in 'us-west-2' region, yeah?

**Comment by PatrickXYS** [comment]
After investigation, region settings are not the root cause. Let's keep the investigation and updated.

**Comment by Jeffwan** [comment]
@PatrickXYS 

Can you extract region as an argument? Why do we stick to `us-west-2` now?
